### ISSUE TITLE
Try to use `inspect.isawaitable` instead of iscoroutinefunction if available

### ISSUE THREAD

**Issue by Rapptz** [aio-libs/sphinxcontrib-asyncio#4]
Certain things return `asyncio.Future` or something a la `loop.create_future` or even something with `__await__`. The auto documenter should try to fetch these cases and tag them appropriately with `comethod`/`cofunction` if found.

**Comment by asvetlov** [comment]
Makes sense.
Would you create a PR?
The PR should use `isawaitable` if awailable and switch back to current approach on old Python versions (Python 3.4 I guess) like we do for [ensure_future](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L27-L30)

**Comment by Rapptz** [comment]
Actually it turns out that this is a bit trickier than I originally proposed. `isawaitable` doesn't work on function objects (as expected in hind sight I suppose), it only works on already created objects. 

Ergo, there's no good way of doing what I propose.
