### ISSUE TITLE
Missing Changelog entry for 0.3.0

### ISSUE THREAD

**Issue by sebix** [aio-libs/sphinxcontrib-asyncio#8]
Version 0.3.0 was recently published, but the [CHANGES.rst](https://github.com/aio-libs/sphinxcontrib-asyncio/blob/master/CHANGES.rst) does not contain a section for the new version. Could you please summarize the changes of that version there? Thanks!

**Comment by asvetlov** [comment]
Done.
Basically, the 0.3 release fixes compatibility issues with Sphinx 3
